movies_list = [
    {"title": "Inside Out 2", "rating": "7.9", "genre": "Animation, Adventure, Comedy", "year": 2024, "director": "Kelsey Mann", "IMDb URL": "https://www.imdb.com/title/tt22022452"},
    {"title": "Furiosa: A Mad Max Saga", "rating": "7.7", "genre": "Action, Adventure, Sci-Fi", "year": 2024, "director": "George Miller", "IMDb URL": "https://www.imdb.com/title/tt12037194"},
    {"title": "Nosferatu", "rating": "N/A", "genre": "Horror", "year": 2024, "director": "Robert Eggers", "IMDb URL": "https://www.imdb.com/title/tt5040012"},
    {"title": "A Quiet Place: Day One", "rating": "6.8", "genre": "Drama, Horror, Sci-Fi", "year": 2024, "director": "Michael Sarnoski", "IMDb URL": "https://www.imdb.com/title/tt13433802"},
    {"title": "The Little Mermaid", "rating": "7.2", "genre": "Adventure, Family, Fantasy", "year": 2023, "director": "Rob Marshall", "IMDb URL": "https://www.imdb.com/title/tt5971474"},
    {"title": "Oppenheimer", "rating": "8.4", "genre": "Biography, Drama, History", "year": 2023, "director": "Christopher Nolan", "IMDb URL": "https://www.imdb.com/title/tt15398776"},
    {"title": "Spider-Man: Across the Spider-Verse", "rating": "8.6", "genre": "Animation, Action, Adventure", "year": 2023, "director": "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson", "IMDb URL": "https://www.imdb.com/title/tt9362722"},
    {"title": "The Flash", "rating": "7.0", "genre": "Action, Adventure, Fantasy", "year": 2023, "director": "Andy Muschietti", "IMDb URL": "https://www.imdb.com/title/tt0439572"},
    {"title": "Guardians of the Galaxy Vol. 3", "rating": "8.2", "genre": "Action, Adventure, Comedy", "year": 2023, "director": "James Gunn", "IMDb URL": "https://www.imdb.com/title/tt6791350"},
    {"title": "Indiana Jones and the Dial of Destiny", "rating": "6.9", "genre": "Action, Adventure", "year": 2023, "director": "James Mangold", "IMDb URL": "https://www.imdb.com/title/tt1462764"},
    {"title": "Barbie", "rating": "7.4", "genre": "Adventure, Comedy, Fantasy", "year": 2023, "director": "Greta Gerwig", "IMDb URL": "https://www.imdb.com/title/tt1517268"},
    {"title": "Elemental", "rating": "7.0", "genre": "Animation, Adventure, Comedy", "year": 2023, "director": "Peter Sohn", "IMDb URL": "https://www.imdb.com/title/tt15789038"},
    {"title": "The Marvels", "rating": "6.1", "genre": "Action, Adventure, Comedy", "year": 2023, "director": "Nia DaCosta", "IMDb URL": "https://www.imdb.com/title/tt10676048"},
    {"title": "Dune: Part Two", "rating": "N/A", "genre": "Action, Adventure, Drama", "year": 2024, "director": "Denis Villeneuve", "IMDb URL": "https://www.imdb.com/title/tt15239678"},
    {"title": "Mission: Impossible - Dead Reckoning Part One", "rating": "7.6", "genre": "Action, Adventure, Thriller", "year": 2023, "director": "Christopher McQuarrie", "IMDb URL": "https://www.imdb.com/title/tt9603212"},
    {"title": "The Batman", "rating": "8.1", "genre": "Action, Crime, Drama", "year": 2022, "director": "Matt Reeves", "IMDb URL": "https://www.imdb.com/title/tt1877830"},
    {"title": "Top Gun: Maverick", "rating": "8.3", "genre": "Action, Drama", "year": 2022, "director": "Joseph Kosinski", "IMDb URL": "https://www.imdb.com/title/tt1745960"},
    {"title": "Avatar: The Way of Water", "rating": "7.8", "genre": "Action, Adventure, Fantasy", "year": 2022, "director": "James Cameron", "IMDb URL": "https://www.imdb.com/title/tt1630029"},
    {"title": "The Whale", "rating": "8.0", "genre": "Drama", "year": 2022, "director": "Darren Aronofsky", "IMDb URL": "https://www.imdb.com/title/tt13833688"},
    {"title": "Black Panther: Wakanda Forever", "rating": "7.3", "genre": "Action, Adventure, Drama", "year": 2022, "director": "Ryan Coogler", "IMDb URL": "https://www.imdb.com/title/tt9114286"},
    {"title": "The Super Mario Bros. Movie", "rating": "7.4", "genre": "Animation, Adventure, Comedy", "year": 2023, "director": "Aaron Horvath, Michael Jelenic", "IMDb URL": "https://www.imdb.com/title/tt6718170"},
    {"title": "Aquaman and the Lost Kingdom", "rating": "N/A", "genre": "Action, Adventure, Fantasy", "year": 2023, "director": "James Wan", "IMDb URL": "https://www.imdb.com/title/tt9663764"},
    {"title": "Wonka", "rating": "N/A", "genre": "Adventure, Comedy, Family", "year": 2023, "director": "Paul King", "IMDb URL": "https://www.imdb.com/title/tt6856242"},
    {"title": "The Marvels", "rating": "6.1", "genre": "Action, Adventure, Comedy", "year": 2023, "director": "Nia DaCosta", "IMDb URL": "https://www.imdb.com/title/tt10676048"},
    {"title": "Shazam! Fury of the Gods", "rating": "6.0", "genre": "Action, Adventure, Comedy", "year": 2023, "director": "David F. Sandberg", "IMDb URL": "https://www.imdb.com/title/tt10151854"},
    {"title": "Ant-Man and the Wasp: Quantumania", "rating": "6.4", "genre": "Action, Adventure, Comedy", "year": 2023, "director": "Peyton Reed", "IMDb URL": "https://www.imdb.com/title/tt10954600"},
    {"title": "John Wick: Chapter 4", "rating": "8.1", "genre": "Action, Crime, Thriller", "year": 2023, "director": "Chad Stahelski", "IMDb URL": "https://www.imdb.com/title/tt10366206"},
    {"title": "Fast X", "rating": "6.0", "genre": "Action, Adventure, Crime", "year": 2023, "director": "Louis Leterrier", "IMDb URL": "https://www.imdb.com/title/tt5433140"}
]
